[package]
name = "vte"
version = "0.3.1"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0 OR MIT"
description = "Parser for implementing terminal emulators"
keywords = ["ansi", "vte", "parser", "terminal"]
repository = "https://github.com/jwilm/vte"
documentation = "https://docs.rs/vte/"

[dependencies.utf8parse]
path = "./utf8parse"
version = "0.1"
